redis:
    image: redis
db:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
vote:
    image: prahaskattimani/vote-app:votingapp
    ports:
       - 5000:80
    links:
       - redis:redis
result:
    image: prahaskattimani/result-app:votingapp
    ports:
       - 5001:80
    links:
       - redis:redis
       - db:db
worker:
    image: prahaskattimani/worker-app:votingapp
    links:
       - redis:redis
       - db:db
