redis:
    image: redis
db:
    image: postgres:9.4
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
vote:
    image: prahaskattimani/vote-app
    ports:
        - 5000:80
    link:
        - redis:redis
results:
    image: prahaskattimani/result-app
    ports:
        - 5001:80
    link:
        - redis:redis
        - db:db
worker:
    image: prahaskattimani/worker-app
    link:
        - redis:redis
        - db:db
