apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    name: result-pod
    app: example-voting-app
spec:
  containers:
    - name: results
      image: prahaskattmiani/result-app
      ports:
      - containerPort: 80
