apiVersion: v1
kind: Service
metadata:
  name: voting-service
  app: example-voting-app  
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
      name: voting-app-pod
      app: example-voting-app
