apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: example-voting-app
spec:
  containers:
    - name: voting-app
      image: prahaskattimani/vote-app
      ports:
      - containerPort: 80
